version: '3.7'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: client:latest
    restart: always
    container_name: client
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    # ports:
    #   - 3000:80
    networks:
      - homepage
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: server:latest
    restart: always
    container_name: server
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - redis
    # ports:
    #   - 5000:5000
    networks:
      - homepage
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./db.dump:/db.dump 
    # ports:
    #   - 27017:27017
    networks:
      - homepage
  redis: 
    image: redis:latest
    restart: always
    container_name: redis
    # ports:
    #   - 6379:6379
    networks:
      - homepage
    depends_on:
      - mongo
  proxy: 
    image: nginx:stable-alpine
    restart: always
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - client
    networks:
      - homepage

networks:
  homepage:
    driver: bridge

