# Use an official Node.js image as the base image
FROM node:16

ENV NODE_ENV production 

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY server/package*.json ./

# Install the dependencies
RUN npm install

COPY server/ ./

# Expose port 80 for incoming HTTP requests
EXPOSE 5000

# Start the Nginx server
CMD ["npm", "run", "prod"]